### ISSUE TITLE
Improve Project section

### ISSUE THREAD

**Issue by lupionpe** [blk-app/homepage#6]
### What is the feature?

Put description, job and gifs from work on Project section

### Page

https://blk.app.br

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
```[tasklist]
### Tasks
- [ ] https://github.com/blk-app/homepage/issues/7
- [ ] https://github.com/blk-app/wiki/issues/92
- [ ] https://github.com/blk-app/homepage/issues/13
- [x] Use GPT to get key-word
- [x] Get webpage ready for Ads
- [x] Pay for key-words
```

**Comment by lupionpe** [comment]
Reference:
http://www.geoja.com.br/
http://hiparc.com.br/
https://nuvve.com.br/agricultura/
https://www.attamgeo.com.br/
http://geosolid.com.br/
https://www.flymapengenharia.com/
http://www.geoassessoria.com/index.php
